<?php
/**
 * @see Bricks_Checkout_Block_Adminhtml_Edit_Fields_Type_Text
 */

/* @var Bricks_Checkout_Helper_Data $helper $helper */
$helper = Mage::helper('bricks_checkout');
ob_start();
?>
<table class="border" cellpadding="0" cellspacing="0">
	<tr class="headings">
		<th class="type-price"><?php echo $helper->__( 'Price' ); ?></th>
	</tr>

	<tr><td><input type="text" class="input-text validate-number field-price" id="<?php echo $helper->getFieldId('{{field_id}}_price'); ?>" name="<?php echo $helper->getFieldName( array( '{{field_id}}', 'price' ) ); ?>" value="{{price}}" /></td></tr>
</table>
<?php $script = ob_get_clean(); ?>
<script type="text/javascript">
//<![CDATA[
FieldTemplateText = <?php echo Mage::helper('core')->jsonEncode( $script ); ?>;
//]]>
</script>
