<?php
/* @var $model Bricks_Checkout_Model_Step */
$model = $this->getModel();
$id = $model->getId();
$this->addCheckoutStepsJs();
?>
<form action="" id="checkout-step-<?php echo $id;  ?>">
	<div id="checkout-step-<?php echo $id; ?>-load">
		<!-- Content loaded dynamically -->
	</div>

	<div id="onepage-checkout-step-<?php echo $id; ?>-additional-load">
		<?php echo $this->getChildHtml('additional') ?>
	</div>

	<div class="buttons-set" id="step-<?php echo $id; ?>-buttons-container">
		<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
		<button type="button" class="button" onclick="customCheckoutStep<?php echo $id; ?>.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
		<span id="step-<?php echo $id; ?>-please-wait" class="please-wait" style="display:none;">
			<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
		</span>
	</div>

	<input type="hidden" name="step" value="<?php echo $id; ?>" />
</form>

<script type="text/javascript">
	var customCheckoutStep<?php echo $id; ?> = new CustomCheckoutStep( <?php echo $id; ?>, '<?php echo $this->getUrl( 'checkout/onepage/saveCustomStep' ); ?>' );
</script>