<?php
/* @var $model Bricks_Checkout_Model_Field */
$model = $this->getFormField();
$saved = unserialize( $this->getFieldSavedValue() );
$baseName = $this->getFormFieldName();
$required = ( $model->getIsRequire() ) ? 'required-entry' : false;
?>
<li class="control" <?php if ( $model->getIsRequire() ) { ?>class="required"<?php } ?>>
	<dl>
		<dt>
			<label>
				<?php echo $model->getTitle(); ?>
				<?php if ( $model->getIsRequire() ): ?>
				<em>*</em>
				<?php endif; ?>
			</labael>
		</dt>

		<dd>
			<ul>
				<?php foreach ( $model->getValues()->getData() as $option ): ?>
					<li>
						<input <?php if ( isset( $saved[ $option['field_value_id'] ] ) ) { ?>checked="checked"<?php } ?> type="checkbox" id="field-<?php echo $model->getId(); ?>-<?php echo $option['field_value_id']; ?>" class="checkbox" name="<?php echo $baseName; ?>[<?php echo $option['field_value_id']; ?>]" />
						<label for="field-<?php echo $model->getId(); ?>-<?php echo $option['field_value_id']; ?>"><?php echo $option['title']; ?></label>
					</li>
				<?php endforeach; ?>
			</ul>
		</dd>
	</dl>
</li>