<?php

$data = $this->getOrder()->getCustomStepsData();

$class = 'right';
foreach ( $data as $values ) :
	$class = ( $class == 'right' ) ? 'left' : 'right';
	$value = reset( $values );
	$title = Mage::getSingleton('bricks_checkout/sale_order')->load( $value['sale_order_id'] );
?>
	<div class="box-<?php echo $class; ?>">
		<div class="entry-edit">
			<div class="entry-edit-head"><h4 class="block-head"><?php echo $title->getTitle(); ?></h4></div>
			<div class="fieldset">
				<table cellspacing="0" class="form-list">
					<?php foreach ( $values as $value ): ?>
						<tr>
							<td class="label"><label for="field-<?php echo $value['sale_order_value_id']; ?>"><?php echo $value['name'] ?></label></td>
							<td class="value"><?php echo nl2br( $value['value'] ); ?></td>
						</tr>
					<?php endforeach; ?>
				</table>
			</div>
		</div>
	</div>
<?php
endforeach;